version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "dweinholz"
      - "eKatchko"
      - "vktrrdk"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"


