language: node_js
node_js:
  - 8.13.0
services:
  - docker
install:
  - npm install -g angular-cli
  - npm install
script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then audit-ci --moderate; fi
  # Check code style
  - ng lint
  - docker build -t webapp  .
