FROM node:8-alpine as builder

COPY package.json  ./

RUN npm set progress=false && npm config set depth 0 && npm cache clean --force

## Storing node modules on a separate layer will prevent unnecessary npm installs at each build
#RUN npm i && mkdir /ng-app && cp -R ./node_modules ./ng-app
RUN mkdir /ng-app

WORKDIR /ng-app

RUN rm -rf node_modules && npm install && npm install -g @angular/cli
