name: E2E Tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/test_as_action'


jobs:

  # Wait for up to a minute for previous run to complete, abort if not done by then
  pre-ci:
    runs-on: self-hosted
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci-tests:
    needs: pre-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Persistent Environment Json
        run:  cp ~/persistent/environment.json ./e2e
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install NPM Packages
        run: npm install
      - name: Run Tests
        run: npm run e2e

