name: build-image
on: pull_request
jobs:   
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Workflow run cleanup action
              uses: rokroskar/workflow-run-cleanup-action@ee1451b869ba1e381729b3d40489997021f0d562 # v0.3.3
              env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - run: docker build --no-cache  -t webapp .
