name: Linting
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'staging'
      - 'dev'
      - 'master'
    tags-ignore:
      - '0.1.0-beta.*'

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci --no-audit --prefer-offline
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true
      # Alternative: if you use npm instead of yarn
      # - run: npm ci --no-audit --prefer-offline
      - uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint 

