name: Linting
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'staging'
      - 'dev'
      - 'master'
    tags-ignore:
      - '0.1.0-beta.*'

jobs:
  tslinting-check:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - run: git status
      - run: npm install npm@8.1.0
      - name: Prepare
        run: npm ci
      - name: Lint
        run: |
          npm i
          npx ng lint cloud-webapp --fix --force
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD -- ':(exclude)package-lock.json'; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v3.11.0
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           commit-message: fix(Linting):blacked code
           title: Automated TsLint Linting [${{github.ref}}]
           body: |
                        New Linting
                        - Fixed Linting Errors
                        - Auto-generated by [create-pull-request][1]
                        [1]: https://github.com/peter-evans/create-pull-request
           labels: automated,linting
           reviewers: ${{github.actor}}
           branch: fix(linting)_${{github.ref}}
      - name: Check outputs
        run: |
                      echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
                      echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
      - name: Check if linting problems still exists
        run:  npx ng lint cloud-webapp



