name: Linting
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'staging'
      - 'dev'
      - 'master'
    tags-ignore:
      - '0.1.0-beta.*'

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: git status
      - name: Prepare
        run: npm ci
      - name: Run ESLint
        run: |
          sudo npm install -g @angular/cli
          sudo npm install eslint --save-dev
          npx eslint --init
          eslint . --ext .js,.jsx,.ts,.tsx



