name: NPM AUDIT

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        sudo npm install -g audit-ci
        audit-ci --config travis/audit-ci.json

    
