name: NPM AUDIT

on: [push]

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
    - name: Workflow run cleanup action
      uses: rokroskar/workflow-run-cleanup-action@v0.3.3
      env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: |
        sudo npm install -g audit-ci
        audit-ci --config audit/audit-ci.json


