name: Check Package

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 5' # every friday AM 8:0
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - uses: MeilCli/npm-update-check-action@v4
      id: outdated

    - name: Rocket.Chat Notification
      uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      if: steps.outdated.outputs.has_npm_update != 'false'
      with:
          type: ${{ job.status }}
          job_name: ':older_man: NPM Outdated'
          mention_if: 'failure'
          mention: 'To see the outdated packages, click on the workflow link and check the workflow output!  -  '
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          token: ${{secrets.GITHUB_TOKEN}}
