name: reviewdog
on: pull_request
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: own iml
        run: |
          curl -L -o ./install-misspell.sh https://git.io/misspell
          sh ./install-misspell.sh
          ./bin/misspell --help
          find . -type f -name '*.ts'   | grep -v node_modules/ | xargs ./bin/misspell -error -w
          echo 'done'
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "Us"
          reporter: "github-pr-check"
          level: "warning"  
