name: reviewdog
on: pull_request
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - name: own iml
        run: |
          curl -L -o ./install-misspell.sh https://git.io/misspell
          sh ./install-misspell.sh
          ./bin/misspell -w -q .
          find . -type f -name '*.ts'   | grep -v node_modules/ | xargs ./bin/misspell -error -w
          git status
          echo 'done'
