name: Create Wiki Issue

on:
  pull_request:
    types: [opened]
    branches-ignore:
      - 'dependabot/**'


jobs:
  wikilinks-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Issue From File
      id: ciff
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: Wiki Update [${{ github.event.pull_request.title }}]
        content-filepath: ./.github/WIKI_ISSUE_TEMPLATE.md
        labels: wiki
        assignees: ${{github.actor}}
    - name: Create or Update Project Card
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-location: deNBI
        project-name: Weekly Sprint
        column-name: Current Sprint
        issue-number: ${{ steps.ciff.outputs.issue-number }}
        token: ${{ secrets.GITHUB_TOKEN }}



